travis:
  secure:
    BINSTAR_TOKEN: 6v2O+NET081qGVCy5/mYRFBW+uu1yTAnC0VwcmO3vOtOzHRcgV0c0PuN4bXpxi154CETdmLunVX9uOXuLbUoeitmewFJku+7jlwGOP9unVIdAhjXNo0iNHccmXfH38CCo/4OelaU+wSuGx73C8O0uht5eYMLX0llQjC+4OMF7M/1RMCR7Xp518djmHkWgmAlhTOsA//5MFcx2PkGxrXWMnFfwSvL3ZH8u5Wr+Q+x18Jsxy/fPiRy3f569orYQbaHPMCX2S7721prQaQZGyz+K6lU18BU9PAfjgAvwBJn1ACFDwHtkVVIdEdfm1pmT1RP/zfHO7Q8QOsXZhIWK4U3Cap3Tx4SbUi4kwll93xDImp9tKzYDUNi8DKLy1hzVxVJNxdg+yJozthoRKtaztpDcmKpSvn7WLzdlgEM9K97rWr2yY7SrNvzMNyZyH5wrjSRGx20aJhETLNiDKgUrSTziAPrUhkvWS7qHciUEKKISMTFAznrsERbU06LPOvSffXNoapg1CaPxVqABQTg4uSJ+Nji7SOF9e363oaGcW/Q46dRSCBOscQII5gx3VkiDKg8AAnp7dAxlC6w+eClRKMXS9NH8e7cPJRSAAILFLx1Dn7GbD6VZXz3pFYy8y5DwXkyghUU14ttxXwcogR8nVInGBmxn3VQkn2qmnJsOWHQ7Z0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
